//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherMap.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsWebRequest
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string Body { get; set; }
        public string RequestMethod { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public string UserAgent { get; set; }
        public string RequestURL { get; set; }
        public string Permission { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
